use super::*;
use crate::Land;
use common::{
    calendar::Calendar,
    terrain::{Block, BlockKind},
};
use rand::prelude::*;
use vek::*;

/// Wings represent the external structure of a building.
/// They are arranged in a tree, with child wings branching off their parents.
/// Wings are defined by an origin on one of their ends, a direction, and a
/// width/length. The connecting face of a child wing must be fully enclosed by
/// the area of its parent. Wings are unconcerned with aesthetics: it is the job
/// of style-driven rendering to turn a set of wings into blocks.
///
/// .------.
/// |      |
/// ^      |
/// |      |
/// x------'
struct Wing {
    origin: Vec2<i32>,
    dir: Dir2,
    // (width, length)
    dim: Vec2<i32>,
    children: Vec<Wing>,
}

impl Wing {
    fn aabr(&self) -> Aabr<i32> {
        let p = self.origin
            + self.dir.rotated_cw().to_vec2() * self.dim.x
            + self.dir.to_vec2() * self.dim.y;
        Aabr {
            min: Vec2::min(self.origin, p),
            max: Vec2::max(self.origin, p),
        }
    }
}

struct Room {
    #[allow(dead_code)]
    aabb: Aabb<i32>,
}

/// Represents house data generated by the `generate()` method
pub struct Building {
    /// Tile position of the door tile
    pub door_tile: Vec2<i32>,
    /// Axis aligned bounding region of tiles
    tile_aabr: Aabr<i32>,
    /// Axis aligned bounding region for the house
    #[allow(dead_code)]
    bounds: Aabr<i32>,
    /// Approximate altitude of the door tile
    pub(crate) alt: i32,
    #[allow(dead_code)]
    rooms: Vec<Room>,
    base: Wing,
}

impl Building {
    pub fn generate(
        land: &Land,
        rng: &mut impl Rng,
        site: &Site,
        door_tile: Vec2<i32>,
        door_dir: Vec2<i32>,
        tile_aabr: Aabr<i32>,
        _calendar: Option<&Calendar>,
        alt: Option<i32>,
    ) -> Self {
        let mut rooms = Vec::new();

        for _ in 0..rng.random_range(2..5) {
            let min = tile_aabr
                .min
                .map2(tile_aabr.max, |min, max| rng.random_range(min..max));
            let max = min.map2(tile_aabr.max, |min, max| rng.random_range(min..max) + 1);
            rooms.push(Room {
                aabb: Aabb {
                    min: min.with_z(0),
                    max: max.with_z(rng.random_range(1..4)),
                },
            });
        }

        fn generate_wing(parent: &mut Wing, _limits: Aabr<i32>, rng: &mut impl Rng) {
            if rng.random_bool(0.5) && parent.dim.y >= 3 {
                let w = rng.random_range(1..=parent.dim.y);
                let is_left = rng.random_bool(0.5);
                let offset = rng.random_range(0..=parent.dim.y - w);
                let mut wing = Wing {
                    dir: if is_left {
                        parent.dir.rotated_cw()
                    } else {
                        parent.dir.rotated_ccw()
                    },
                    origin: parent.origin
                        + if is_left {
                            Vec2::new(-1, 0)
                        } else {
                            parent.dir.rotated_cw().to_vec2() * parent.dim.x
                        }
                        + parent.dir.to_vec2()
                            * if is_left {
                                offset
                            } else {
                                parent.dim.y - 1 - offset
                            },
                    dim: Vec2::new(w, parent.dim.x + rng.random_range(1..3)),
                    children: Vec::new(),
                };
                generate_wing(&mut wing, _limits, rng);
                parent.children.push(wing);
            }
        }

        let mut base = Wing {
            dir: Dir2::Y,
            dim: Vec2::new(2, 3),
            origin: Vec2::new((tile_aabr.min.x + tile_aabr.max.x) / 2, tile_aabr.min.y),
            children: Vec::new(),
        };
        generate_wing(&mut base, tile_aabr, rng);

        Self {
            door_tile,
            tile_aabr,
            bounds: Aabr {
                min: site.tile_wpos(tile_aabr.min),
                max: site.tile_wpos(tile_aabr.max),
            },
            alt: alt.unwrap_or_else(|| {
                land.get_alt_approx(site.tile_center_wpos(door_tile + door_dir)) as i32
            }),
            rooms,
            base,
        }
    }

    fn walk_wing(
        &self,
        wing: &Wing,
        site: &Site,
        painter: &Painter,
        _interior: &mut PrimitiveRef,
        body: &mut PrimitiveRef,
        roof: &mut PrimitiveRef,
        depth: i32,
    ) {
        let aabr = wing.aabr();
        let aabb = Aabb {
            min: site.tile_wpos(aabr.min).with_z(self.alt),
            max: site.tile_wpos(aabr.max).with_z(self.alt + 10 - depth * 3) + 1,
        };
        *body = body.union(painter.aabb(aabb));
        *roof = roof.union(
            painter.vault(
                Aabb {
                    min: aabb.min.xy().with_z(aabb.max.z),
                    max: aabb
                        .max
                        .xy()
                        .with_z(aabb.max.z + wing.dim.x * TILE_SIZE as i32 / 2),
                },
                wing.dir,
            ),
        );
        for child in &wing.children {
            self.walk_wing(child, site, painter, _interior, body, roof, depth + 1);
        }
    }
}

impl Structure for Building {
    #[cfg(feature = "dyn-lib")]
    #[unsafe(export_name = "as_dyn_structure_building")]
    fn as_dyn_outer(&self) -> Option<(&dyn Structure, &'static str)> {
        Some((Self::as_dyn_impl(self), "as_dyn_structure_building"))
    }

    fn spawn_rules_inner(
        &self,
        spawn_rules: &mut SpawnRules,
        _land: &Land,
        _wpos: Vec2<i32>,
        weight: f32,
    ) {
        spawn_rules.prefer_alt(self.alt as f32, weight * 1.0);
    }

    fn render_inner(&self, site: &Site, _land: &Land, painter: &Painter) {
        const ROOM_HEIGHT: i32 = 5;
        let mut interior = painter.empty();
        let mut body = painter.empty();
        let mut frame = painter.empty();
        let mut roof = painter.empty();

        self.walk_wing(
            &self.base,
            site,
            painter,
            &mut interior,
            &mut body,
            &mut roof,
            0,
        );

        for room in &self.rooms {
            let min = site
                .tile_wpos(room.aabb.min.xy())
                .with_z(self.alt + room.aabb.min.z * ROOM_HEIGHT);
            let max = site
                .tile_wpos(room.aabb.max.xy())
                .with_z(self.alt + room.aabb.max.z * ROOM_HEIGHT)
                + 1;

            const EAVES: i32 = 1;

            // Interior
            interior = interior.union(painter.aabb(Aabb {
                min: min + 1,
                max: max - 1,
            }));

            // Body
            body = body.union(painter.aabb(Aabb { min, max }));

            // Roof
            roof = roof.union(
                painter.pyramid(Aabb {
                    min: (min.xy() - EAVES).with_z(max.z),
                    max: (max.xy() + EAVES)
                        .with_z(max.z + (max.xy() - min.xy()).reduce_min() + EAVES * 2),
                }),
            );

            // Frame
            for tile in util::aabb_iter(room.aabb) {
                let min = site
                    .tile_wpos(tile.xy())
                    .with_z(self.alt + tile.z * ROOM_HEIGHT);
                let max = min + Vec2::broadcast(TILE_SIZE as i32).with_z(ROOM_HEIGHT) + 1;
                frame = frame.union(
                    painter
                        .aabb(Aabb { min, max })
                        .without(painter.aabb(Aabb {
                            min: min + 1 - Vec3::unit_x(),
                            max: max - 1 + Vec3::unit_x(),
                        }))
                        .without(painter.aabb(Aabb {
                            min: min + 1 - Vec3::unit_y(),
                            max: max - 1 + Vec3::unit_y(),
                        }))
                        .without(painter.aabb(Aabb {
                            min: min + 1 - Vec3::unit_z(),
                            max: max - 1 + Vec3::unit_z(),
                        })),
                );
            }
        }

        // Base
        painter
            .aabb(Aabb {
                min: (site.tile_wpos(self.tile_aabr.min) - 1).with_z(self.alt - 10),
                max: (site.tile_wpos(self.tile_aabr.max) + 2).with_z(self.alt),
            })
            .fill(Fill::Block(Block::new(
                BlockKind::Rock,
                Rgb::new(50, 50, 60),
            )));
        // Interior
        body.without(interior).fill(Fill::Block(Block::new(
            BlockKind::Wood,
            Rgb::new(180, 120, 70),
        )));
        // Roof
        roof.fill(Fill::Block(Block::new(
            BlockKind::Wood,
            Rgb::new(100, 30, 10),
        )));
        // Frame
        frame.fill(Fill::Block(Block::new(
            BlockKind::Wood,
            Rgb::new(100, 70, 50),
        )));
        // Door
        painter
            .aabb(Aabb {
                min: (site.tile_wpos(self.door_tile)).with_z(self.alt),
                max: (site.tile_wpos(self.door_tile + 1)).with_z(self.alt + 10),
            })
            .fill(Fill::Block(Block::new(
                BlockKind::Wood,
                Rgb::new(50, 70, 50),
            )));
    }
}
