[package]
name = "veloren-beta-auth"
version = "0.18.0"
edition = "2024"

[dependencies]
argon2 = "0.5"
axum = { version = "0.8", features = ["json", "tokio"] }
fxhash = "0.2"
hex = "0.4"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
serde_json = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "signal", "sync"] }
uuid = { version = "1.0", features = ["fast-rng", "serde", "v5"] }
bs58 = "0.5"
ed25519-dalek = "2"
